"""safe align models non-destructive 2025-08-23

Revision ID: 9dbe94486d67
Revises: 86171b66491f
Create Date: 2025-08-23 04:03:14.357513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dbe94486d67'
down_revision: Union[str, None] = '86171b66491f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ab_test_participants_id'), 'ab_test_participants', ['id'], unique=False)
    op.alter_column('event_participations', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_participations', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_event_participations_event_id'), 'event_participations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participations_id'), 'event_participations', ['id'], unique=False)
    op.create_index(op.f('ix_event_participations_user_id'), 'event_participations', ['user_id'], unique=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_game_history_action_type'), 'game_history', ['action_type'], unique=False)
    op.create_index(op.f('ix_game_history_created_at'), 'game_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_game_history_game_type'), 'game_history', ['game_type'], unique=False)
    op.create_index(op.f('ix_game_history_session_id'), 'game_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_game_history_user_id'), 'game_history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'game_history', 'game_sessions', ['session_id'], ['id'])
    op.create_index(op.f('ix_game_sessions_external_session_id'), 'game_sessions', ['external_session_id'], unique=True)
    op.create_index(op.f('ix_game_sessions_game_type'), 'game_sessions', ['game_type'], unique=False)
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_game_sessions_status'), 'game_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.add_column('invite_codes', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.add_column('invite_codes', sa.Column('used_by_user_id', sa.Integer(), nullable=True))
    op.add_column('invite_codes', sa.Column('used_at', sa.DateTime(), nullable=True))
    op.alter_column('invite_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('invite_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    op.create_foreign_key(None, 'invite_codes', 'users', ['used_by_user_id'], ['id'])
    op.create_foreign_key(None, 'invite_codes', 'users', ['created_by'], ['id'])
    op.alter_column('missions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('shop_discounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('shop_limited_packages', 'emergency_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('shop_limited_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('shop_products', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('shop_products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('shop_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_shop_products_deleted_at'), 'shop_products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shop_products_product_id'), 'shop_products', ['product_id'], unique=True)
    op.alter_column('shop_promo_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_shop_promo_codes_code'), 'shop_promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_shop_promo_usage_promo_code'), 'shop_promo_usage', ['promo_code'], unique=False)
    op.add_column('shop_transactions', sa.Column('extra', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_shop_transactions_idempotency_key'), 'shop_transactions', ['idempotency_key'], unique=False)
    op.alter_column('token_blacklist', 'blacklisted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_token_blacklist_jti', table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_user_actions_id'), 'user_actions', ['id'], unique=False)
    op.create_foreign_key(None, 'user_actions', 'users', ['user_id'], ['id'])
    op.alter_column('user_missions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_missions', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_user_missions_id'), 'user_missions', ['id'], unique=False)
    op.create_index(op.f('ix_user_missions_mission_id'), 'user_missions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_user_missions_user_id'), 'user_missions', ['user_id'], unique=False)
    op.alter_column('user_rewards', 'reward_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_rewards_claimed_at'), 'user_rewards', ['claimed_at'], unique=False)
    op.alter_column('user_segments', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_segments_id'), 'user_segments', ['id'], unique=False)
    op.create_index(op.f('ix_user_segments_rfm_group'), 'user_segments', ['rfm_group'], unique=False)
    op.create_unique_constraint(None, 'user_segments', ['user_id'])
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'vip_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'vip_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_segments', type_='unique')
    op.drop_index(op.f('ix_user_segments_rfm_group'), table_name='user_segments')
    op.drop_index(op.f('ix_user_segments_id'), table_name='user_segments')
    op.alter_column('user_segments', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_rewards_claimed_at'), table_name='user_rewards')
    op.alter_column('user_rewards', 'reward_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_user_missions_user_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_mission_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_id'), table_name='user_missions')
    op.alter_column('user_missions', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_missions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'user_actions', type_='foreignkey')
    op.drop_index(op.f('ix_user_actions_id'), table_name='user_actions')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.create_index('ix_token_blacklist_jti', 'token_blacklist', ['jti'], unique=False)
    op.alter_column('token_blacklist', 'blacklisted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_shop_transactions_idempotency_key'), table_name='shop_transactions')
    op.drop_column('shop_transactions', 'extra')
    op.drop_index(op.f('ix_shop_promo_usage_promo_code'), table_name='shop_promo_usage')
    op.drop_index(op.f('ix_shop_promo_codes_code'), table_name='shop_promo_codes')
    op.alter_column('shop_promo_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_shop_products_product_id'), table_name='shop_products')
    op.drop_index(op.f('ix_shop_products_deleted_at'), table_name='shop_products')
    op.alter_column('shop_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('shop_products', 'deleted_at')
    op.drop_column('shop_products', 'extra')
    op.alter_column('shop_limited_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('shop_limited_packages', 'emergency_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shop_discounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.alter_column('missions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'invite_codes', type_='foreignkey')
    op.drop_constraint(None, 'invite_codes', type_='foreignkey')
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.alter_column('invite_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('invite_codes', 'used_at')
    op.drop_column('invite_codes', 'used_by_user_id')
    op.drop_column('invite_codes', 'is_used')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_status'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_game_type'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_external_session_id'), table_name='game_sessions')
    op.drop_constraint(None, 'game_history', type_='foreignkey')
    op.drop_index(op.f('ix_game_history_user_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_session_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_game_type'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_created_at'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_action_type'), table_name='game_history')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_event_participations_user_id'), table_name='event_participations')
    op.drop_index(op.f('ix_event_participations_id'), table_name='event_participations')
    op.drop_index(op.f('ix_event_participations_event_id'), table_name='event_participations')
    op.alter_column('event_participations', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('event_participations', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_ab_test_participants_id'), table_name='ab_test_participants')
    # ### end Alembic commands ###
