"""safe align models non-destructive 2025-08-23

Revision ID: 9dbe94486d67
Revises: 86171b66491f
Create Date: 2025-08-23 04:03:14.357513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = '9dbe94486d67'
down_revision: Union[str, None] = '86171b66491f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = Inspector.from_engine(conn)  # type: ignore
    # Guard: create index only if missing to avoid duplicate index errors
    existing_abtest_indexes = {i['name'] for i in insp.get_indexes('ab_test_participants')}
    if 'ix_ab_test_participants_id' not in existing_abtest_indexes:
        op.create_index(op.f('ix_ab_test_participants_id'), 'ab_test_participants', ['id'], unique=False)
    op.alter_column('event_participations', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_participations', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    existing_evt_indexes = {i['name'] for i in insp.get_indexes('event_participations')}
    if 'ix_event_participations_event_id' not in existing_evt_indexes:
        op.create_index(op.f('ix_event_participations_event_id'), 'event_participations', ['event_id'], unique=False)
    if 'ix_event_participations_id' not in existing_evt_indexes:
        op.create_index(op.f('ix_event_participations_id'), 'event_participations', ['id'], unique=False)
    if 'ix_event_participations_user_id' not in existing_evt_indexes:
        op.create_index(op.f('ix_event_participations_user_id'), 'event_participations', ['user_id'], unique=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    existing_events_indexes = {i['name'] for i in insp.get_indexes('events')}
    if 'ix_events_id' not in existing_events_indexes:
        op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    existing_gh_indexes = {i['name'] for i in insp.get_indexes('game_history')}
    if 'ix_game_history_action_type' not in existing_gh_indexes:
        op.create_index(op.f('ix_game_history_action_type'), 'game_history', ['action_type'], unique=False)
    if 'ix_game_history_created_at' not in existing_gh_indexes:
        op.create_index(op.f('ix_game_history_created_at'), 'game_history', ['created_at'], unique=False)
    if 'ix_game_history_game_type' not in existing_gh_indexes:
        op.create_index(op.f('ix_game_history_game_type'), 'game_history', ['game_type'], unique=False)
    if 'ix_game_history_session_id' not in existing_gh_indexes:
        op.create_index(op.f('ix_game_history_session_id'), 'game_history', ['session_id'], unique=False)
    if 'ix_game_history_user_id' not in existing_gh_indexes:
        op.create_index(op.f('ix_game_history_user_id'), 'game_history', ['user_id'], unique=False)
    existing_gh_fks = insp.get_foreign_keys('game_history')
    existing_gh_fk_specs = {(
        tuple(fk.get('constrained_columns') or []),
        fk.get('referred_table'),
        tuple(fk.get('referred_columns') or []),
    ) for fk in existing_gh_fks}
    if (('session_id',), 'game_sessions', ('id',)) not in existing_gh_fk_specs:
        op.create_foreign_key('fk_game_history_session', 'game_history', 'game_sessions', ['session_id'], ['id'])
    existing_gs_indexes = {i['name'] for i in insp.get_indexes('game_sessions')}
    if 'ix_game_sessions_external_session_id' not in existing_gs_indexes:
        op.create_index(op.f('ix_game_sessions_external_session_id'), 'game_sessions', ['external_session_id'], unique=True)
    if 'ix_game_sessions_game_type' not in existing_gs_indexes:
        op.create_index(op.f('ix_game_sessions_game_type'), 'game_sessions', ['game_type'], unique=False)
    if 'ix_game_sessions_id' not in existing_gs_indexes:
        op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    if 'ix_game_sessions_status' not in existing_gs_indexes:
        op.create_index(op.f('ix_game_sessions_status'), 'game_sessions', ['status'], unique=False)
    if 'ix_game_sessions_user_id' not in existing_gs_indexes:
        op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    existing_invite_cols = {c['name'] for c in insp.get_columns('invite_codes')}
    if 'is_used' not in existing_invite_cols:
        op.add_column('invite_codes', sa.Column('is_used', sa.Boolean(), nullable=True))
    if 'used_by_user_id' not in existing_invite_cols:
        op.add_column('invite_codes', sa.Column('used_by_user_id', sa.Integer(), nullable=True))
    if 'used_at' not in existing_invite_cols:
        op.add_column('invite_codes', sa.Column('used_at', sa.DateTime(), nullable=True))
    op.alter_column('invite_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('invite_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    existing_invite_indexes = {i['name'] for i in insp.get_indexes('invite_codes')}
    if 'ix_invite_codes_code' not in existing_invite_indexes:
        op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    if 'ix_invite_codes_id' not in existing_invite_indexes:
        op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    # FKs (guarded)
    existing_ic_fks = insp.get_foreign_keys('invite_codes')
    existing_ic_fk_specs = {(
        tuple(fk.get('constrained_columns') or []),
        fk.get('referred_table'),
        tuple(fk.get('referred_columns') or []),
    ) for fk in existing_ic_fks}
    if (('used_by_user_id',), 'users', ('id',)) not in existing_ic_fk_specs:
        op.create_foreign_key('fk_invite_codes_used_by_user', 'invite_codes', 'users', ['used_by_user_id'], ['id'])
    if (('created_by',), 'users', ('id',)) not in existing_ic_fk_specs:
        op.create_foreign_key('fk_invite_codes_created_by', 'invite_codes', 'users', ['created_by'], ['id'])
    op.alter_column('missions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    existing_missions_indexes = {i['name'] for i in insp.get_indexes('missions')}
    if 'ix_missions_id' not in existing_missions_indexes:
        op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    existing_rt_indexes = {i['name'] for i in insp.get_indexes('refresh_tokens')}
    if 'ix_refresh_tokens_id' not in existing_rt_indexes:
        op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    if 'ix_refresh_tokens_token' not in existing_rt_indexes:
        op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    existing_rt_fks = insp.get_foreign_keys('refresh_tokens')
    existing_rt_fk_specs = {(
        tuple(fk.get('constrained_columns') or []),
        fk.get('referred_table'),
        tuple(fk.get('referred_columns') or []),
    ) for fk in existing_rt_fks}
    if (('user_id',), 'users', ('id',)) not in existing_rt_fk_specs:
        op.create_foreign_key('fk_refresh_tokens_user', 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('shop_discounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('shop_limited_packages', 'emergency_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('shop_limited_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    existing_sp_cols = {c['name'] for c in insp.get_columns('shop_products')}
    if 'extra' not in existing_sp_cols:
        op.add_column('shop_products', sa.Column('extra', sa.JSON(), nullable=True))
    if 'deleted_at' not in existing_sp_cols:
        op.add_column('shop_products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('shop_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    existing_sp_indexes = {i['name'] for i in insp.get_indexes('shop_products')}
    if 'ix_shop_products_deleted_at' not in existing_sp_indexes:
        op.create_index(op.f('ix_shop_products_deleted_at'), 'shop_products', ['deleted_at'], unique=False)
    if 'ix_shop_products_product_id' not in existing_sp_indexes:
        op.create_index(op.f('ix_shop_products_product_id'), 'shop_products', ['product_id'], unique=True)
    op.alter_column('shop_promo_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    existing_spc_indexes = {i['name'] for i in insp.get_indexes('shop_promo_codes')}
    # Guard unique index on shop_promo_codes(code)
    if 'ix_shop_promo_codes_code' not in existing_spc_indexes:
        op.create_index(op.f('ix_shop_promo_codes_code'), 'shop_promo_codes', ['code'], unique=True)
    existing_spu_indexes = {i['name'] for i in insp.get_indexes('shop_promo_usage')}
    if 'ix_shop_promo_usage_promo_code' not in existing_spu_indexes:
        op.create_index(op.f('ix_shop_promo_usage_promo_code'), 'shop_promo_usage', ['promo_code'], unique=False)
    # shop_transactions.extra column (JSON) may already exist in drifted schemas
    existing_st_cols = {c['name'] for c in insp.get_columns('shop_transactions')}
    if 'extra' not in existing_st_cols:
        op.add_column('shop_transactions', sa.Column('extra', sa.JSON(), nullable=True))
    existing_st_indexes = {i['name'] for i in insp.get_indexes('shop_transactions')}
    if 'ix_shop_transactions_idempotency_key' not in existing_st_indexes:
        op.create_index(op.f('ix_shop_transactions_idempotency_key'), 'shop_transactions', ['idempotency_key'], unique=False)
    op.alter_column('token_blacklist', 'blacklisted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # Guard token_blacklist indexes to avoid duplicates in drifted schemas
    existing_tb_indexes = {i['name'] for i in insp.get_indexes('token_blacklist')}
    # Ensure unique index on jti exists
    if 'ix_token_blacklist_jti' not in existing_tb_indexes:
        op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    # Ensure unique index on token exists
    if 'ix_token_blacklist_token' not in existing_tb_indexes:
        op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # Ensure id index exists (non-unique)
    if 'ix_token_blacklist_id' not in existing_tb_indexes:
        op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    existing_ua_indexes = {i['name'] for i in insp.get_indexes('user_actions')}
    if 'ix_user_actions_id' not in existing_ua_indexes:
        op.create_index(op.f('ix_user_actions_id'), 'user_actions', ['id'], unique=False)
    existing_ua_fks = insp.get_foreign_keys('user_actions')
    existing_ua_fk_specs = {(
        tuple(fk.get('constrained_columns') or []),
        fk.get('referred_table'),
        tuple(fk.get('referred_columns') or []),
    ) for fk in existing_ua_fks}
    if (('user_id',), 'users', ('id',)) not in existing_ua_fk_specs:
        op.create_foreign_key('fk_user_actions_user', 'user_actions', 'users', ['user_id'], ['id'])
    op.alter_column('user_missions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_missions', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    existing_um_indexes = {i['name'] for i in insp.get_indexes('user_missions')}
    if 'ix_user_missions_id' not in existing_um_indexes:
        op.create_index(op.f('ix_user_missions_id'), 'user_missions', ['id'], unique=False)
    if 'ix_user_missions_mission_id' not in existing_um_indexes:
        op.create_index(op.f('ix_user_missions_mission_id'), 'user_missions', ['mission_id'], unique=False)
    if 'ix_user_missions_user_id' not in existing_um_indexes:
        op.create_index(op.f('ix_user_missions_user_id'), 'user_missions', ['user_id'], unique=False)
    # Guard: only alter/index if user_rewards table exists
    existing_tables = set(insp.get_table_names())
    if 'user_rewards' in existing_tables:
        op.alter_column('user_rewards', 'reward_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        existing_ur_indexes = {i['name'] for i in insp.get_indexes('user_rewards')}
        if 'ix_user_rewards_claimed_at' not in existing_ur_indexes:
            op.create_index(op.f('ix_user_rewards_claimed_at'), 'user_rewards', ['claimed_at'], unique=False)
    op.alter_column('user_segments', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    existing_us_indexes = {i['name'] for i in insp.get_indexes('user_segments')}
    if 'ix_user_segments_id' not in existing_us_indexes:
        op.create_index(op.f('ix_user_segments_id'), 'user_segments', ['id'], unique=False)
    if 'ix_user_segments_rfm_group' not in existing_us_indexes:
        op.create_index(op.f('ix_user_segments_rfm_group'), 'user_segments', ['rfm_group'], unique=False)
    # Guard unique(user_id) on user_segments
    existing_us_uniques = insp.get_unique_constraints('user_segments')
    if not any(set(u.get('column_names') or []) == {'user_id'} for u in existing_us_uniques):
        op.create_unique_constraint(None, 'user_segments', ['user_id'])
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    existing_use_indexes = {i['name'] for i in insp.get_indexes('user_sessions')}
    if 'ix_user_sessions_id' not in existing_use_indexes:
        op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    existing_use_fks = insp.get_foreign_keys('user_sessions')
    existing_use_fk_specs = {(
        tuple(fk.get('constrained_columns') or []),
        fk.get('referred_table'),
        tuple(fk.get('referred_columns') or []),
    ) for fk in existing_use_fks}
    if (('user_id',), 'users', ('id',)) not in existing_use_fk_specs:
        op.create_foreign_key('fk_user_sessions_user', 'user_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'vip_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    existing_users_indexes = {i['name'] for i in insp.get_indexes('users')}
    if 'ix_users_id' not in existing_users_indexes:
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if 'ix_users_site_id' not in existing_users_indexes:
        op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=True)
    existing_users_uniques = insp.get_unique_constraints('users')
    if not any(set(u.get('column_names') or []) == {'phone_number'} for u in existing_users_uniques):
        op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'vip_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'STANDARD'::character varying"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.alter_column('user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_segments', type_='unique')
    op.drop_index(op.f('ix_user_segments_rfm_group'), table_name='user_segments')
    op.drop_index(op.f('ix_user_segments_id'), table_name='user_segments')
    op.alter_column('user_segments', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Guard: drop indexes/alter only if user_rewards table exists
    bind = op.get_bind()
    try:
        inspector = sa.inspect(bind)
        has_user_rewards = 'user_rewards' in set(inspector.get_table_names())
    except Exception:
        has_user_rewards = False
    if has_user_rewards:
        try:
            op.drop_index(op.f('ix_user_rewards_claimed_at'), table_name='user_rewards')
        except Exception:
            pass
        try:
            op.alter_column('user_rewards', 'reward_id',
                       existing_type=sa.INTEGER(),
                       nullable=False)
        except Exception:
            pass
    op.drop_index(op.f('ix_user_missions_user_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_mission_id'), table_name='user_missions')
    op.drop_index(op.f('ix_user_missions_id'), table_name='user_missions')
    op.alter_column('user_missions', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_missions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'user_actions', type_='foreignkey')
    op.drop_index(op.f('ix_user_actions_id'), table_name='user_actions')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=False)
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.create_index('ix_token_blacklist_jti', 'token_blacklist', ['jti'], unique=False)
    op.alter_column('token_blacklist', 'blacklisted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_shop_transactions_idempotency_key'), table_name='shop_transactions')
    op.drop_column('shop_transactions', 'extra')
    op.drop_index(op.f('ix_shop_promo_usage_promo_code'), table_name='shop_promo_usage')
    op.drop_index(op.f('ix_shop_promo_codes_code'), table_name='shop_promo_codes')
    op.alter_column('shop_promo_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_shop_products_product_id'), table_name='shop_products')
    op.drop_index(op.f('ix_shop_products_deleted_at'), table_name='shop_products')
    op.alter_column('shop_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('shop_products', 'deleted_at')
    op.drop_column('shop_products', 'extra')
    op.alter_column('shop_limited_packages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('shop_limited_packages', 'emergency_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('shop_discounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.alter_column('missions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'invite_codes', type_='foreignkey')
    op.drop_constraint(None, 'invite_codes', type_='foreignkey')
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.alter_column('invite_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('invite_codes', 'used_at')
    op.drop_column('invite_codes', 'used_by_user_id')
    op.drop_column('invite_codes', 'is_used')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_status'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_game_type'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_external_session_id'), table_name='game_sessions')
    op.drop_constraint(None, 'game_history', type_='foreignkey')
    op.drop_index(op.f('ix_game_history_user_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_session_id'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_game_type'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_created_at'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_action_type'), table_name='game_history')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_event_participations_user_id'), table_name='event_participations')
    op.drop_index(op.f('ix_event_participations_id'), table_name='event_participations')
    op.drop_index(op.f('ix_event_participations_event_id'), table_name='event_participations')
    op.alter_column('event_participations', 'progress_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('event_participations', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_ab_test_participants_id'), table_name='ab_test_participants')
    # ### end Alembic commands ###
