FROM node:20-alpine

WORKDIR /app

# Copy manifest files first to leverage Docker layer caching
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install --legacy-peer-deps --no-audit --no-fund

# Copy app source
COPY . .

# Run Next dev binding to all interfaces
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
